name: Run Unit Test on Push
on: 
    push:
        branches:
               -main

jobs:
    build:
        runs-on: ubunto-latest

        steps:
            - users: actions/checkout@v3
  
            - name: Set up .Net
              uses: actions/setup-dotnet@v3
              with:
                    dotnet-versions: "9.x"

            - name: restore dependencies
              run: dotnet restore

            - name: Run unit test
              run: dotnet test